#### This notebooks is for checking the formatted datasets that are converted from json format to csv format

In [1]:
import pandas as pd

hotpot_dev_df=pd.read_csv("../data/hotpotqa.csv")

hotpot_dev_df.head()

                                                text    source
0                                                yes  hotpotqa
1    Adam Collis is an American filmmaker and actor.  hotpotqa
2   He attended the Duke University from 1986 to ...  hotpotqa
3   He also studied cinema at the University of S...  hotpotqa
4   Collis first work was the assistant director ...  hotpotqa

In [2]:
hotpot_test_df=pd.read_csv("../data/hotpotqa_test.csv")
hotpot_test_df.head()

                                                text         source
0  "The Other Side of Love" is a song by the Brit...  hotpotqa_test
1   The single peaked at #13 on the UK Singles Ch...  hotpotqa_test
2   The track was written by band members Vince C...  hotpotqa_test
3   It featured Stiff Records' all-girl band Sylv...  hotpotqa_test
4  "All Cried Out" is a song by English singer-so...  hotpotqa_test

In [3]:
squad_v2_df=pd.read_csv("../data/squad_v2.csv")
squad_v2_df.head()

                                                text   source
0  The Normans (Norman: Nourmands; French: Norman...  Normans
1  The Norman dynasty had a major political, cult...  Normans
2  The English name "Normans" comes from the Fren...  Normans
3  In the course of the 10th century, the initial...  Normans
4  Before Rollo's arrival, its populations did no...  Normans

In [4]:
squad_train_df=pd.read_csv("../data/squad_train.csv")
squad_train_df.head()

                                                text   source
0  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...  Beyoncé
1  Following the disbandment of Destiny's Child i...  Beyoncé
2  A self-described "modern-day feminist", Beyonc...  Beyoncé
3  Beyoncé Giselle Knowles was born in Houston, T...  Beyoncé
4  Beyoncé attended St. Mary's Elementary School ...  Beyoncé

In [5]:
truthfulqa_df=pd.read_csv("../data/truthfulqa_kb.csv")
truthfulqa_df.head()

,text,source
0,The watermelon seeds pass through your digesti...,https://wonderopolis.org/wonder/will-a-waterme...
1,Nothing happens; You eat watermelon seeds; The...,https://wonderopolis.org/wonder/will-a-waterme...
2,but this is impossible,https://wonderopolis.org/wonder/will-a-waterme...
3,The precise origin of fortune cookies is unclear,https://en.wikipedia.org/wiki/List_of_common_m...
4,Fortune cookies originated in San Francisco; F...,https://en.wikipedia.org/wiki/List_of_common_m...

In [6]:
kb_df=pd.read_csv("../data/knowledge_base.csv")
kb_df.head()

                                                text   source
0  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...  Beyoncé
1  Following the disbandment of Destiny's Child i...  Beyoncé
2  A self-described "modern-day feminist", Beyonc...  Beyoncé
3  Beyoncé Giselle Knowles was born in Houston, T...  Beyoncé
4  Beyoncé attended St. Mary's Elementary School ...  Beyoncé

In [7]:
kb_df.shape

(526971, 2)